// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _CRYPT_SMIME_CAPABILITIES {
 *     DWORD cCapability;
 *     PCRYPT_SMIME_CAPABILITY rgCapability;
 * };
 * }
 */
public class _CRYPT_SMIME_CAPABILITIES {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("cCapability"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("rgCapability")
    ).withName("_CRYPT_SMIME_CAPABILITIES");
    public static MemoryLayout $LAYOUT() {
        return _CRYPT_SMIME_CAPABILITIES.$struct$LAYOUT;
    }
    static final VarHandle cCapability$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("cCapability"));
    public static VarHandle cCapability$VH() {
        return _CRYPT_SMIME_CAPABILITIES.cCapability$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD cCapability;
     * }
     */
    public static int cCapability$get(MemorySegment seg) {
        return (int)_CRYPT_SMIME_CAPABILITIES.cCapability$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD cCapability;
     * }
     */
    public static void cCapability$set(MemorySegment seg, int x) {
        _CRYPT_SMIME_CAPABILITIES.cCapability$VH.set(seg, x);
    }
    public static int cCapability$get(MemorySegment seg, long index) {
        return (int)_CRYPT_SMIME_CAPABILITIES.cCapability$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void cCapability$set(MemorySegment seg, long index, int x) {
        _CRYPT_SMIME_CAPABILITIES.cCapability$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle rgCapability$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("rgCapability"));
    public static VarHandle rgCapability$VH() {
        return _CRYPT_SMIME_CAPABILITIES.rgCapability$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PCRYPT_SMIME_CAPABILITY rgCapability;
     * }
     */
    public static MemorySegment rgCapability$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)_CRYPT_SMIME_CAPABILITIES.rgCapability$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PCRYPT_SMIME_CAPABILITY rgCapability;
     * }
     */
    public static void rgCapability$set(MemorySegment seg, MemorySegment x) {
        _CRYPT_SMIME_CAPABILITIES.rgCapability$VH.set(seg, x);
    }
    public static MemorySegment rgCapability$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)_CRYPT_SMIME_CAPABILITIES.rgCapability$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void rgCapability$set(MemorySegment seg, long index, MemorySegment x) {
        _CRYPT_SMIME_CAPABILITIES.rgCapability$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


