// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _MEMORY_BASIC_INFORMATION32 {
 *     DWORD BaseAddress;
 *     DWORD AllocationBase;
 *     DWORD AllocationProtect;
 *     DWORD RegionSize;
 *     DWORD State;
 *     DWORD Protect;
 *     DWORD Type;
 * };
 * }
 */
public class _MEMORY_BASIC_INFORMATION32 {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("BaseAddress"),
        Constants$root.C_LONG$LAYOUT.withName("AllocationBase"),
        Constants$root.C_LONG$LAYOUT.withName("AllocationProtect"),
        Constants$root.C_LONG$LAYOUT.withName("RegionSize"),
        Constants$root.C_LONG$LAYOUT.withName("State"),
        Constants$root.C_LONG$LAYOUT.withName("Protect"),
        Constants$root.C_LONG$LAYOUT.withName("Type")
    ).withName("_MEMORY_BASIC_INFORMATION32");
    public static MemoryLayout $LAYOUT() {
        return _MEMORY_BASIC_INFORMATION32.$struct$LAYOUT;
    }
    static final VarHandle BaseAddress$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("BaseAddress"));
    public static VarHandle BaseAddress$VH() {
        return _MEMORY_BASIC_INFORMATION32.BaseAddress$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD BaseAddress;
     * }
     */
    public static int BaseAddress$get(MemorySegment seg) {
        return (int)_MEMORY_BASIC_INFORMATION32.BaseAddress$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD BaseAddress;
     * }
     */
    public static void BaseAddress$set(MemorySegment seg, int x) {
        _MEMORY_BASIC_INFORMATION32.BaseAddress$VH.set(seg, x);
    }
    public static int BaseAddress$get(MemorySegment seg, long index) {
        return (int)_MEMORY_BASIC_INFORMATION32.BaseAddress$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void BaseAddress$set(MemorySegment seg, long index, int x) {
        _MEMORY_BASIC_INFORMATION32.BaseAddress$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle AllocationBase$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("AllocationBase"));
    public static VarHandle AllocationBase$VH() {
        return _MEMORY_BASIC_INFORMATION32.AllocationBase$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD AllocationBase;
     * }
     */
    public static int AllocationBase$get(MemorySegment seg) {
        return (int)_MEMORY_BASIC_INFORMATION32.AllocationBase$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD AllocationBase;
     * }
     */
    public static void AllocationBase$set(MemorySegment seg, int x) {
        _MEMORY_BASIC_INFORMATION32.AllocationBase$VH.set(seg, x);
    }
    public static int AllocationBase$get(MemorySegment seg, long index) {
        return (int)_MEMORY_BASIC_INFORMATION32.AllocationBase$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void AllocationBase$set(MemorySegment seg, long index, int x) {
        _MEMORY_BASIC_INFORMATION32.AllocationBase$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle AllocationProtect$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("AllocationProtect"));
    public static VarHandle AllocationProtect$VH() {
        return _MEMORY_BASIC_INFORMATION32.AllocationProtect$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD AllocationProtect;
     * }
     */
    public static int AllocationProtect$get(MemorySegment seg) {
        return (int)_MEMORY_BASIC_INFORMATION32.AllocationProtect$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD AllocationProtect;
     * }
     */
    public static void AllocationProtect$set(MemorySegment seg, int x) {
        _MEMORY_BASIC_INFORMATION32.AllocationProtect$VH.set(seg, x);
    }
    public static int AllocationProtect$get(MemorySegment seg, long index) {
        return (int)_MEMORY_BASIC_INFORMATION32.AllocationProtect$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void AllocationProtect$set(MemorySegment seg, long index, int x) {
        _MEMORY_BASIC_INFORMATION32.AllocationProtect$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle RegionSize$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("RegionSize"));
    public static VarHandle RegionSize$VH() {
        return _MEMORY_BASIC_INFORMATION32.RegionSize$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD RegionSize;
     * }
     */
    public static int RegionSize$get(MemorySegment seg) {
        return (int)_MEMORY_BASIC_INFORMATION32.RegionSize$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD RegionSize;
     * }
     */
    public static void RegionSize$set(MemorySegment seg, int x) {
        _MEMORY_BASIC_INFORMATION32.RegionSize$VH.set(seg, x);
    }
    public static int RegionSize$get(MemorySegment seg, long index) {
        return (int)_MEMORY_BASIC_INFORMATION32.RegionSize$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void RegionSize$set(MemorySegment seg, long index, int x) {
        _MEMORY_BASIC_INFORMATION32.RegionSize$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle State$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("State"));
    public static VarHandle State$VH() {
        return _MEMORY_BASIC_INFORMATION32.State$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD State;
     * }
     */
    public static int State$get(MemorySegment seg) {
        return (int)_MEMORY_BASIC_INFORMATION32.State$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD State;
     * }
     */
    public static void State$set(MemorySegment seg, int x) {
        _MEMORY_BASIC_INFORMATION32.State$VH.set(seg, x);
    }
    public static int State$get(MemorySegment seg, long index) {
        return (int)_MEMORY_BASIC_INFORMATION32.State$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void State$set(MemorySegment seg, long index, int x) {
        _MEMORY_BASIC_INFORMATION32.State$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle Protect$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("Protect"));
    public static VarHandle Protect$VH() {
        return _MEMORY_BASIC_INFORMATION32.Protect$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD Protect;
     * }
     */
    public static int Protect$get(MemorySegment seg) {
        return (int)_MEMORY_BASIC_INFORMATION32.Protect$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD Protect;
     * }
     */
    public static void Protect$set(MemorySegment seg, int x) {
        _MEMORY_BASIC_INFORMATION32.Protect$VH.set(seg, x);
    }
    public static int Protect$get(MemorySegment seg, long index) {
        return (int)_MEMORY_BASIC_INFORMATION32.Protect$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Protect$set(MemorySegment seg, long index, int x) {
        _MEMORY_BASIC_INFORMATION32.Protect$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle Type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("Type"));
    public static VarHandle Type$VH() {
        return _MEMORY_BASIC_INFORMATION32.Type$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD Type;
     * }
     */
    public static int Type$get(MemorySegment seg) {
        return (int)_MEMORY_BASIC_INFORMATION32.Type$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD Type;
     * }
     */
    public static void Type$set(MemorySegment seg, int x) {
        _MEMORY_BASIC_INFORMATION32.Type$VH.set(seg, x);
    }
    public static int Type$get(MemorySegment seg, long index) {
        return (int)_MEMORY_BASIC_INFORMATION32.Type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Type$set(MemorySegment seg, long index, int x) {
        _MEMORY_BASIC_INFORMATION32.Type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


