// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _NDR_SCONTEXT {
 *     void* pad[2];
 *     void* userContext;
 * };
 * }
 */
public class _NDR_SCONTEXT {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(2, Constants$root.C_POINTER$LAYOUT).withName("pad"),
        Constants$root.C_POINTER$LAYOUT.withName("userContext")
    ).withName("_NDR_SCONTEXT");
    public static MemoryLayout $LAYOUT() {
        return _NDR_SCONTEXT.$struct$LAYOUT;
    }
    public static MemorySegment pad$slice(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    static final VarHandle userContext$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("userContext"));
    public static VarHandle userContext$VH() {
        return _NDR_SCONTEXT.userContext$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* userContext;
     * }
     */
    public static MemorySegment userContext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)_NDR_SCONTEXT.userContext$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* userContext;
     * }
     */
    public static void userContext$set(MemorySegment seg, MemorySegment x) {
        _NDR_SCONTEXT.userContext$VH.set(seg, x);
    }
    public static MemorySegment userContext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)_NDR_SCONTEXT.userContext$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void userContext$set(MemorySegment seg, long index, MemorySegment x) {
        _NDR_SCONTEXT.userContext$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


