// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _OLESTREAMVTBL {
 *     DWORD (*Get)(LPOLESTREAM,void*,DWORD);
 *     DWORD (*Put)(LPOLESTREAM,void*,DWORD);
 * };
 * }
 */
public class _OLESTREAMVTBL {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("Get"),
        Constants$root.C_POINTER$LAYOUT.withName("Put")
    ).withName("_OLESTREAMVTBL");
    public static MemoryLayout $LAYOUT() {
        return _OLESTREAMVTBL.$struct$LAYOUT;
    }
    static final FunctionDescriptor Get$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final FunctionDescriptor Get_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle Get_UP$MH = RuntimeHelper.upcallHandle(Get.class, "apply", _OLESTREAMVTBL.Get_UP$FUNC);
    static final FunctionDescriptor Get_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle Get_DOWN$MH = RuntimeHelper.downcallHandle(
        _OLESTREAMVTBL.Get_DOWN$FUNC
    );
    /**
     * {@snippet :
 * DWORD (*Get)(LPOLESTREAM,void*,DWORD);
     * }
     */
    public interface Get {

        int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, int _x2);
        static MemorySegment allocate(Get fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(_OLESTREAMVTBL.Get_UP$MH, fi, _OLESTREAMVTBL.Get$FUNC, scope);
        }
        static Get ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, int __x2) -> {
                try {
                    return (int)_OLESTREAMVTBL.Get_DOWN$MH.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Get$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("Get"));
    public static VarHandle Get$VH() {
        return _OLESTREAMVTBL.Get$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD (*Get)(LPOLESTREAM,void*,DWORD);
     * }
     */
    public static MemorySegment Get$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)_OLESTREAMVTBL.Get$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD (*Get)(LPOLESTREAM,void*,DWORD);
     * }
     */
    public static void Get$set(MemorySegment seg, MemorySegment x) {
        _OLESTREAMVTBL.Get$VH.set(seg, x);
    }
    public static MemorySegment Get$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)_OLESTREAMVTBL.Get$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Get$set(MemorySegment seg, long index, MemorySegment x) {
        _OLESTREAMVTBL.Get$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Get Get(MemorySegment segment, SegmentScope scope) {
        return Get.ofAddress(Get$get(segment), scope);
    }
    static final FunctionDescriptor Put$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final FunctionDescriptor Put_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle Put_UP$MH = RuntimeHelper.upcallHandle(Put.class, "apply", _OLESTREAMVTBL.Put_UP$FUNC);
    static final FunctionDescriptor Put_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle Put_DOWN$MH = RuntimeHelper.downcallHandle(
        _OLESTREAMVTBL.Put_DOWN$FUNC
    );
    /**
     * {@snippet :
 * DWORD (*Put)(LPOLESTREAM,void*,DWORD);
     * }
     */
    public interface Put {

        int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, int _x2);
        static MemorySegment allocate(Put fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(_OLESTREAMVTBL.Put_UP$MH, fi, _OLESTREAMVTBL.Put$FUNC, scope);
        }
        static Put ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, int __x2) -> {
                try {
                    return (int)_OLESTREAMVTBL.Put_DOWN$MH.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Put$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("Put"));
    public static VarHandle Put$VH() {
        return _OLESTREAMVTBL.Put$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD (*Put)(LPOLESTREAM,void*,DWORD);
     * }
     */
    public static MemorySegment Put$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)_OLESTREAMVTBL.Put$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD (*Put)(LPOLESTREAM,void*,DWORD);
     * }
     */
    public static void Put$set(MemorySegment seg, MemorySegment x) {
        _OLESTREAMVTBL.Put$VH.set(seg, x);
    }
    public static MemorySegment Put$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)_OLESTREAMVTBL.Put$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Put$set(MemorySegment seg, long index, MemorySegment x) {
        _OLESTREAMVTBL.Put$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Put Put(MemorySegment segment, SegmentScope scope) {
        return Put.ofAddress(Put$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


