// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct tagAXESLISTA AXESLISTA;
 * }
 */
public final class AXESLISTA extends tagAXESLISTA {

    // Suppresses default constructor, ensuring non-instantiability.
    private AXESLISTA() {}
}


