// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _BYTE_SIZEDARR BYTE_SIZEDARR;
 * }
 */
public final class BYTE_SIZEDARR extends _BYTE_SIZEDARR {

    // Suppresses default constructor, ensuring non-instantiability.
    private BYTE_SIZEDARR() {}
}


