// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$673 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$673() {}
    static final FunctionDescriptor RPC_SETFILTER_FUNC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor RPC_SETFILTER_FUNC_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RPC_SETFILTER_FUNC_UP$MH = RuntimeHelper.upcallHandle(RPC_SETFILTER_FUNC.class, "apply", constants$673.RPC_SETFILTER_FUNC_UP$FUNC);
    static final FunctionDescriptor RPC_SETFILTER_FUNC_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RPC_SETFILTER_FUNC_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$673.RPC_SETFILTER_FUNC_DOWN$FUNC
    );
    static final FunctionDescriptor I_RpcServerStartListening$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcServerStartListening$MH = RuntimeHelper.downcallHandle(
        "I_RpcServerStartListening",
        constants$673.I_RpcServerStartListening$FUNC
    );
    static final FunctionDescriptor I_RpcServerStopListening$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle I_RpcServerStopListening$MH = RuntimeHelper.downcallHandle(
        "I_RpcServerStopListening",
        constants$673.I_RpcServerStopListening$FUNC
    );
    static final FunctionDescriptor RPC_BLOCKING_FN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor RPC_BLOCKING_FN_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RPC_BLOCKING_FN_UP$MH = RuntimeHelper.upcallHandle(RPC_BLOCKING_FN.class, "apply", constants$673.RPC_BLOCKING_FN_UP$FUNC);
    static final FunctionDescriptor RPC_BLOCKING_FN_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RPC_BLOCKING_FN_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$673.RPC_BLOCKING_FN_DOWN$FUNC
    );
}


