// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$689 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$689() {}
    static final FunctionDescriptor RpcNsBindingImportBeginW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcNsBindingImportBeginW$MH = RuntimeHelper.downcallHandle(
        "RpcNsBindingImportBeginW",
        constants$689.RpcNsBindingImportBeginW$FUNC
    );
    static final FunctionDescriptor RpcNsBindingImportNext$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcNsBindingImportNext$MH = RuntimeHelper.downcallHandle(
        "RpcNsBindingImportNext",
        constants$689.RpcNsBindingImportNext$FUNC
    );
    static final FunctionDescriptor RpcNsBindingImportDone$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcNsBindingImportDone$MH = RuntimeHelper.downcallHandle(
        "RpcNsBindingImportDone",
        constants$689.RpcNsBindingImportDone$FUNC
    );
    static final FunctionDescriptor RpcNsBindingSelect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcNsBindingSelect$MH = RuntimeHelper.downcallHandle(
        "RpcNsBindingSelect",
        constants$689.RpcNsBindingSelect$FUNC
    );
    static final FunctionDescriptor RPCNOTIFICATION_ROUTINE$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final FunctionDescriptor RPCNOTIFICATION_ROUTINE_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RPCNOTIFICATION_ROUTINE_UP$MH = RuntimeHelper.upcallHandle(RPCNOTIFICATION_ROUTINE.class, "apply", constants$689.RPCNOTIFICATION_ROUTINE_UP$FUNC);
    static final FunctionDescriptor RPCNOTIFICATION_ROUTINE_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RPCNOTIFICATION_ROUTINE_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$689.RPCNOTIFICATION_ROUTINE_DOWN$FUNC
    );
}


