// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$113 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$113() {}
    static final FunctionDescriptor SetEnvironmentStringsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetEnvironmentStringsW$MH = RuntimeHelper.downcallHandle(
        "SetEnvironmentStringsW",
        constants$113.SetEnvironmentStringsW$FUNC
    );
    static final FunctionDescriptor GetStdHandle$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetStdHandle$MH = RuntimeHelper.downcallHandle(
        "GetStdHandle",
        constants$113.GetStdHandle$FUNC
    );
    static final FunctionDescriptor SetStdHandle$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetStdHandle$MH = RuntimeHelper.downcallHandle(
        "SetStdHandle",
        constants$113.SetStdHandle$FUNC
    );
    static final FunctionDescriptor SetStdHandleEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetStdHandleEx$MH = RuntimeHelper.downcallHandle(
        "SetStdHandleEx",
        constants$113.SetStdHandleEx$FUNC
    );
    static final FunctionDescriptor GetCommandLineA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle GetCommandLineA$MH = RuntimeHelper.downcallHandle(
        "GetCommandLineA",
        constants$113.GetCommandLineA$FUNC
    );
    static final FunctionDescriptor GetCommandLineW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle GetCommandLineW$MH = RuntimeHelper.downcallHandle(
        "GetCommandLineW",
        constants$113.GetCommandLineW$FUNC
    );
}


