// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$633 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$633() {}
    static final FunctionDescriptor RpcBindingInqOption$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingInqOption$MH = RuntimeHelper.downcallHandle(
        "RpcBindingInqOption",
        constants$633.RpcBindingInqOption$FUNC
    );
    static final FunctionDescriptor RpcBindingFromStringBindingA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingFromStringBindingA$MH = RuntimeHelper.downcallHandle(
        "RpcBindingFromStringBindingA",
        constants$633.RpcBindingFromStringBindingA$FUNC
    );
    static final FunctionDescriptor RpcBindingFromStringBindingW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingFromStringBindingW$MH = RuntimeHelper.downcallHandle(
        "RpcBindingFromStringBindingW",
        constants$633.RpcBindingFromStringBindingW$FUNC
    );
    static final FunctionDescriptor RpcSsGetContextBinding$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcSsGetContextBinding$MH = RuntimeHelper.downcallHandle(
        "RpcSsGetContextBinding",
        constants$633.RpcSsGetContextBinding$FUNC
    );
    static final FunctionDescriptor RpcBindingInqMaxCalls$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingInqMaxCalls$MH = RuntimeHelper.downcallHandle(
        "RpcBindingInqMaxCalls",
        constants$633.RpcBindingInqMaxCalls$FUNC
    );
    static final FunctionDescriptor RpcBindingInqObject$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingInqObject$MH = RuntimeHelper.downcallHandle(
        "RpcBindingInqObject",
        constants$633.RpcBindingInqObject$FUNC
    );
}


