// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$872 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$872() {}
    static final FunctionDescriptor SCardGetReaderDeviceInstanceIdA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardGetReaderDeviceInstanceIdA$MH = RuntimeHelper.downcallHandle(
        "SCardGetReaderDeviceInstanceIdA",
        constants$872.SCardGetReaderDeviceInstanceIdA$FUNC
    );
    static final FunctionDescriptor SCardGetReaderDeviceInstanceIdW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardGetReaderDeviceInstanceIdW$MH = RuntimeHelper.downcallHandle(
        "SCardGetReaderDeviceInstanceIdW",
        constants$872.SCardGetReaderDeviceInstanceIdW$FUNC
    );
    static final FunctionDescriptor SCardListReadersWithDeviceInstanceIdA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardListReadersWithDeviceInstanceIdA$MH = RuntimeHelper.downcallHandle(
        "SCardListReadersWithDeviceInstanceIdA",
        constants$872.SCardListReadersWithDeviceInstanceIdA$FUNC
    );
    static final FunctionDescriptor SCardListReadersWithDeviceInstanceIdW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardListReadersWithDeviceInstanceIdW$MH = RuntimeHelper.downcallHandle(
        "SCardListReadersWithDeviceInstanceIdW",
        constants$872.SCardListReadersWithDeviceInstanceIdW$FUNC
    );
    static final FunctionDescriptor SCardAudit$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SCardAudit$MH = RuntimeHelper.downcallHandle(
        "SCardAudit",
        constants$872.SCardAudit$FUNC
    );
    static final FunctionDescriptor LPFNPSPCALLBACKA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor LPFNPSPCALLBACKA_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LPFNPSPCALLBACKA_UP$MH = RuntimeHelper.upcallHandle(LPFNPSPCALLBACKA.class, "apply", constants$872.LPFNPSPCALLBACKA_UP$FUNC);
}


