// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1530 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1530() {}
    static final MemorySegment CERT_CHAIN_CROSS_CERT_DOWNLOAD_INTERVAL_HOURS_VALUE_NAME$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("C");
    static final MemorySegment CERT_CHAIN_CRL_VALIDITY_EXT_PERIOD_HOURS_VALUE_NAME$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("C");
    static final MemorySegment HCCE_CURRENT_USER$ADDR = MemorySegment.ofAddress(0L);
    static final MemorySegment HCCE_LOCAL_MACHINE$ADDR = MemorySegment.ofAddress(1L);
    static final MemorySegment HCCE_SERIAL_LOCAL_MACHINE$ADDR = MemorySegment.ofAddress(2L);
    static final MemorySegment REVOCATION_OID_CRL_REVOCATION$ADDR = MemorySegment.ofAddress(1L);
}


