// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$993 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$993() {}
    static final FunctionDescriptor LPFNCANUNLOADNOW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final FunctionDescriptor LPFNCANUNLOADNOW_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle LPFNCANUNLOADNOW_UP$MH = RuntimeHelper.upcallHandle(LPFNCANUNLOADNOW.class, "apply", constants$993.LPFNCANUNLOADNOW_UP$FUNC);
    static final FunctionDescriptor LPFNCANUNLOADNOW_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle LPFNCANUNLOADNOW_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$993.LPFNCANUNLOADNOW_DOWN$FUNC
    );
    static final FunctionDescriptor DllGetClassObject$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DllGetClassObject$MH = RuntimeHelper.downcallHandle(
        "DllGetClassObject",
        constants$993.DllGetClassObject$FUNC
    );
    static final FunctionDescriptor DllCanUnloadNow$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle DllCanUnloadNow$MH = RuntimeHelper.downcallHandle(
        "DllCanUnloadNow",
        constants$993.DllCanUnloadNow$FUNC
    );
    static final FunctionDescriptor CoTaskMemAlloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle CoTaskMemAlloc$MH = RuntimeHelper.downcallHandle(
        "CoTaskMemAlloc",
        constants$993.CoTaskMemAlloc$FUNC
    );
    static final FunctionDescriptor CoTaskMemRealloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle CoTaskMemRealloc$MH = RuntimeHelper.downcallHandle(
        "CoTaskMemRealloc",
        constants$993.CoTaskMemRealloc$FUNC
    );
}


