// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1305 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1305() {}
    static final MemorySegment HKEY_CURRENT_CONFIG$ADDR = MemorySegment.ofAddress(-2147483643L);
    static final MemorySegment HKEY_DYN_DATA$ADDR = MemorySegment.ofAddress(-2147483642L);
    static final MemorySegment HKEY_CURRENT_USER_LOCAL_SETTINGS$ADDR = MemorySegment.ofAddress(-2147483641L);
    static final MemorySegment WIN31_CLASS$ADDR = MemorySegment.ofAddress(0L);
    static final MemorySegment SZDDESYS_TOPIC$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("System");
    static final MemorySegment SZDDESYS_ITEM_TOPICS$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Topics");
}


