// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$986 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$986() {}
    static final FunctionDescriptor CoCreateFreeThreadedMarshaler$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoCreateFreeThreadedMarshaler$MH = RuntimeHelper.downcallHandle(
        "CoCreateFreeThreadedMarshaler",
        constants$986.CoCreateFreeThreadedMarshaler$FUNC
    );
    static final FunctionDescriptor CoFreeUnusedLibraries$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle CoFreeUnusedLibraries$MH = RuntimeHelper.downcallHandle(
        "CoFreeUnusedLibraries",
        constants$986.CoFreeUnusedLibraries$FUNC
    );
    static final FunctionDescriptor CoFreeUnusedLibrariesEx$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CoFreeUnusedLibrariesEx$MH = RuntimeHelper.downcallHandle(
        "CoFreeUnusedLibrariesEx",
        constants$986.CoFreeUnusedLibrariesEx$FUNC
    );
    static final FunctionDescriptor CoDisconnectContext$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CoDisconnectContext$MH = RuntimeHelper.downcallHandle(
        "CoDisconnectContext",
        constants$986.CoDisconnectContext$FUNC
    );
    static final FunctionDescriptor CoInitializeSecurity$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoInitializeSecurity$MH = RuntimeHelper.downcallHandle(
        "CoInitializeSecurity",
        constants$986.CoInitializeSecurity$FUNC
    );
    static final FunctionDescriptor CoGetCallContext$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoGetCallContext$MH = RuntimeHelper.downcallHandle(
        "CoGetCallContext",
        constants$986.CoGetCallContext$FUNC
    );
}


