// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$802 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$802() {}
    static final FunctionDescriptor CryptUpdateProtectedState$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptUpdateProtectedState$MH = RuntimeHelper.downcallHandle(
        "CryptUpdateProtectedState",
        constants$802.CryptUpdateProtectedState$FUNC
    );
    static final FunctionDescriptor CryptProtectMemory$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CryptProtectMemory$MH = RuntimeHelper.downcallHandle(
        "CryptProtectMemory",
        constants$802.CryptProtectMemory$FUNC
    );
    static final FunctionDescriptor CryptUnprotectMemory$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CryptUnprotectMemory$MH = RuntimeHelper.downcallHandle(
        "CryptUnprotectMemory",
        constants$802.CryptUnprotectMemory$FUNC
    );
    static final FunctionDescriptor QueryUsersOnEncryptedFile$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryUsersOnEncryptedFile$MH = RuntimeHelper.downcallHandle(
        "QueryUsersOnEncryptedFile",
        constants$802.QueryUsersOnEncryptedFile$FUNC
    );
    static final FunctionDescriptor QueryRecoveryAgentsOnEncryptedFile$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryRecoveryAgentsOnEncryptedFile$MH = RuntimeHelper.downcallHandle(
        "QueryRecoveryAgentsOnEncryptedFile",
        constants$802.QueryRecoveryAgentsOnEncryptedFile$FUNC
    );
    static final FunctionDescriptor RemoveUsersFromEncryptedFile$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RemoveUsersFromEncryptedFile$MH = RuntimeHelper.downcallHandle(
        "RemoveUsersFromEncryptedFile",
        constants$802.RemoveUsersFromEncryptedFile$FUNC
    );
}


