// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$705 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$705() {}
    static final FunctionDescriptor IsLFNDriveW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IsLFNDriveW$MH = RuntimeHelper.downcallHandle(
        "IsLFNDriveW",
        constants$705.IsLFNDriveW$FUNC
    );
    static final FunctionDescriptor SHEnumerateUnreadMailAccountsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SHEnumerateUnreadMailAccountsA$MH = RuntimeHelper.downcallHandle(
        "SHEnumerateUnreadMailAccountsA",
        constants$705.SHEnumerateUnreadMailAccountsA$FUNC
    );
    static final FunctionDescriptor SHEnumerateUnreadMailAccountsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SHEnumerateUnreadMailAccountsW$MH = RuntimeHelper.downcallHandle(
        "SHEnumerateUnreadMailAccountsW",
        constants$705.SHEnumerateUnreadMailAccountsW$FUNC
    );
    static final FunctionDescriptor SHGetUnreadMailCountA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SHGetUnreadMailCountA$MH = RuntimeHelper.downcallHandle(
        "SHGetUnreadMailCountA",
        constants$705.SHGetUnreadMailCountA$FUNC
    );
    static final FunctionDescriptor SHGetUnreadMailCountW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SHGetUnreadMailCountW$MH = RuntimeHelper.downcallHandle(
        "SHGetUnreadMailCountW",
        constants$705.SHGetUnreadMailCountW$FUNC
    );
    static final FunctionDescriptor SHSetUnreadMailCountA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SHSetUnreadMailCountA$MH = RuntimeHelper.downcallHandle(
        "SHSetUnreadMailCountA",
        constants$705.SHSetUnreadMailCountA$FUNC
    );
}


