// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$546 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$546() {}
    static final FunctionDescriptor DATEFMT_ENUMPROCEXEX_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle DATEFMT_ENUMPROCEXEX_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$546.DATEFMT_ENUMPROCEXEX_DOWN$FUNC
    );
    static final FunctionDescriptor EnumDateFormatsExEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumDateFormatsExEx$MH = RuntimeHelper.downcallHandle(
        "EnumDateFormatsExEx",
        constants$546.EnumDateFormatsExEx$FUNC
    );
    static final FunctionDescriptor TIMEFMT_ENUMPROCEX$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final FunctionDescriptor TIMEFMT_ENUMPROCEX_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle TIMEFMT_ENUMPROCEX_UP$MH = RuntimeHelper.upcallHandle(TIMEFMT_ENUMPROCEX.class, "apply", constants$546.TIMEFMT_ENUMPROCEX_UP$FUNC);
    static final FunctionDescriptor TIMEFMT_ENUMPROCEX_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle TIMEFMT_ENUMPROCEX_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$546.TIMEFMT_ENUMPROCEX_DOWN$FUNC
    );
    static final FunctionDescriptor EnumTimeFormatsEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumTimeFormatsEx$MH = RuntimeHelper.downcallHandle(
        "EnumTimeFormatsEx",
        constants$546.EnumTimeFormatsEx$FUNC
    );
    static final FunctionDescriptor LOCALE_ENUMPROCEX$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final FunctionDescriptor LOCALE_ENUMPROCEX_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LOCALE_ENUMPROCEX_UP$MH = RuntimeHelper.upcallHandle(LOCALE_ENUMPROCEX.class, "apply", constants$546.LOCALE_ENUMPROCEX_UP$FUNC);
}


