// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$976 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$976() {}
    static final StructLayout CLSID_CCDLabelPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDLabelPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDLabelPropertyPage", constants$976.CLSID_CCDLabelPropertyPage$LAYOUT);
    static final StructLayout CLSID_CCDCheckBoxPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDCheckBoxPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDCheckBoxPropertyPage", constants$976.CLSID_CCDCheckBoxPropertyPage$LAYOUT);
    static final StructLayout CLSID_CCDTextBoxPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDTextBoxPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDTextBoxPropertyPage", constants$976.CLSID_CCDTextBoxPropertyPage$LAYOUT);
    static final StructLayout CLSID_CCDOptionButtonPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDOptionButtonPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDOptionButtonPropertyPage", constants$976.CLSID_CCDOptionButtonPropertyPage$LAYOUT);
    static final StructLayout CLSID_CCDListBoxPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDListBoxPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDListBoxPropertyPage", constants$976.CLSID_CCDListBoxPropertyPage$LAYOUT);
    static final StructLayout CLSID_CCDCommandButtonPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDCommandButtonPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDCommandButtonPropertyPage", constants$976.CLSID_CCDCommandButtonPropertyPage$LAYOUT);
}


