// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1269 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1269() {}
    static final FunctionDescriptor ImmSetOpenStatus$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ImmSetOpenStatus$MH = RuntimeHelper.downcallHandle(
        "ImmSetOpenStatus",
        constants$1269.ImmSetOpenStatus$FUNC
    );
    static final FunctionDescriptor ImmGetCompositionFontA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmGetCompositionFontA$MH = RuntimeHelper.downcallHandle(
        "ImmGetCompositionFontA",
        constants$1269.ImmGetCompositionFontA$FUNC
    );
    static final FunctionDescriptor ImmGetCompositionFontW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmGetCompositionFontW$MH = RuntimeHelper.downcallHandle(
        "ImmGetCompositionFontW",
        constants$1269.ImmGetCompositionFontW$FUNC
    );
    static final FunctionDescriptor ImmSetCompositionFontA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmSetCompositionFontA$MH = RuntimeHelper.downcallHandle(
        "ImmSetCompositionFontA",
        constants$1269.ImmSetCompositionFontA$FUNC
    );
    static final FunctionDescriptor ImmSetCompositionFontW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmSetCompositionFontW$MH = RuntimeHelper.downcallHandle(
        "ImmSetCompositionFontW",
        constants$1269.ImmSetCompositionFontW$FUNC
    );
    static final FunctionDescriptor ImmConfigureIMEA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmConfigureIMEA$MH = RuntimeHelper.downcallHandle(
        "ImmConfigureIMEA",
        constants$1269.ImmConfigureIMEA$FUNC
    );
}


