// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$876 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$876() {}
    static final FunctionDescriptor CloseSpoolFileHandle$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CloseSpoolFileHandle$MH = RuntimeHelper.downcallHandle(
        "CloseSpoolFileHandle",
        constants$876.CloseSpoolFileHandle$FUNC
    );
    static final FunctionDescriptor OpenPrinterA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenPrinterA$MH = RuntimeHelper.downcallHandle(
        "OpenPrinterA",
        constants$876.OpenPrinterA$FUNC
    );
    static final FunctionDescriptor OpenPrinterW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenPrinterW$MH = RuntimeHelper.downcallHandle(
        "OpenPrinterW",
        constants$876.OpenPrinterW$FUNC
    );
    static final FunctionDescriptor ResetPrinterA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ResetPrinterA$MH = RuntimeHelper.downcallHandle(
        "ResetPrinterA",
        constants$876.ResetPrinterA$FUNC
    );
    static final FunctionDescriptor ResetPrinterW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ResetPrinterW$MH = RuntimeHelper.downcallHandle(
        "ResetPrinterW",
        constants$876.ResetPrinterW$FUNC
    );
    static final FunctionDescriptor SetJobA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetJobA$MH = RuntimeHelper.downcallHandle(
        "SetJobA",
        constants$876.SetJobA$FUNC
    );
}


