// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1293 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1293() {}
    static final MemorySegment RT_ANICURSOR$ADDR = MemorySegment.ofAddress(21L);
    static final MemorySegment RT_ANIICON$ADDR = MemorySegment.ofAddress(22L);
    static final MemorySegment RT_HTML$ADDR = MemorySegment.ofAddress(23L);
    static final MemorySegment RT_MANIFEST$ADDR = MemorySegment.ofAddress(24L);
    static final MemorySegment CREATEPROCESS_MANIFEST_RESOURCE_ID$ADDR = MemorySegment.ofAddress(1L);
    static final MemorySegment ISOLATIONAWARE_MANIFEST_RESOURCE_ID$ADDR = MemorySegment.ofAddress(2L);
}


