// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$766 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$766() {}
    static final FunctionDescriptor CertSetCTLContextProperty$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertSetCTLContextProperty$MH = RuntimeHelper.downcallHandle(
        "CertSetCTLContextProperty",
        constants$766.CertSetCTLContextProperty$FUNC
    );
    static final FunctionDescriptor CertGetCTLContextProperty$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertGetCTLContextProperty$MH = RuntimeHelper.downcallHandle(
        "CertGetCTLContextProperty",
        constants$766.CertGetCTLContextProperty$FUNC
    );
    static final FunctionDescriptor CertEnumCTLContextProperties$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CertEnumCTLContextProperties$MH = RuntimeHelper.downcallHandle(
        "CertEnumCTLContextProperties",
        constants$766.CertEnumCTLContextProperties$FUNC
    );
    static final FunctionDescriptor CertEnumCTLsInStore$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertEnumCTLsInStore$MH = RuntimeHelper.downcallHandle(
        "CertEnumCTLsInStore",
        constants$766.CertEnumCTLsInStore$FUNC
    );
    static final FunctionDescriptor CertFindSubjectInCTL$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CertFindSubjectInCTL$MH = RuntimeHelper.downcallHandle(
        "CertFindSubjectInCTL",
        constants$766.CertFindSubjectInCTL$FUNC
    );
    static final FunctionDescriptor CertFindCTLInStore$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertFindCTLInStore$MH = RuntimeHelper.downcallHandle(
        "CertFindCTLInStore",
        constants$766.CertFindCTLInStore$FUNC
    );
}


