// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$90 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$90() {}
    static final StructLayout GUID_PROCESSOR_RESPONSIVENESS_EPP_CEILING_1$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_PROCESSOR_RESPONSIVENESS_EPP_CEILING_1$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_PROCESSOR_RESPONSIVENESS_EPP_CEILING_1", constants$90.GUID_PROCESSOR_RESPONSIVENESS_EPP_CEILING_1$LAYOUT);
    static final StructLayout GUID_PROCESSOR_RESPONSIVENESS_PERF_FLOOR$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_PROCESSOR_RESPONSIVENESS_PERF_FLOOR$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_PROCESSOR_RESPONSIVENESS_PERF_FLOOR", constants$90.GUID_PROCESSOR_RESPONSIVENESS_PERF_FLOOR$LAYOUT);
    static final StructLayout GUID_PROCESSOR_RESPONSIVENESS_PERF_FLOOR_1$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_PROCESSOR_RESPONSIVENESS_PERF_FLOOR_1$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_PROCESSOR_RESPONSIVENESS_PERF_FLOOR_1", constants$90.GUID_PROCESSOR_RESPONSIVENESS_PERF_FLOOR_1$LAYOUT);
    static final StructLayout GUID_LOCK_CONSOLE_ON_WAKE$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_LOCK_CONSOLE_ON_WAKE$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_LOCK_CONSOLE_ON_WAKE", constants$90.GUID_LOCK_CONSOLE_ON_WAKE$LAYOUT);
    static final StructLayout GUID_DEVICE_IDLE_POLICY$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVICE_IDLE_POLICY$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVICE_IDLE_POLICY", constants$90.GUID_DEVICE_IDLE_POLICY$LAYOUT);
    static final StructLayout GUID_CONNECTIVITY_IN_STANDBY$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_CONNECTIVITY_IN_STANDBY$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_CONNECTIVITY_IN_STANDBY", constants$90.GUID_CONNECTIVITY_IN_STANDBY$LAYOUT);
}


