// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$231 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$231() {}
    static final FunctionDescriptor PrivilegeCheck$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PrivilegeCheck$MH = RuntimeHelper.downcallHandle(
        "PrivilegeCheck",
        constants$231.PrivilegeCheck$FUNC
    );
    static final FunctionDescriptor PrivilegedServiceAuditAlarmW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle PrivilegedServiceAuditAlarmW$MH = RuntimeHelper.downcallHandle(
        "PrivilegedServiceAuditAlarmW",
        constants$231.PrivilegedServiceAuditAlarmW$FUNC
    );
    static final FunctionDescriptor QuerySecurityAccessMask$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QuerySecurityAccessMask$MH = RuntimeHelper.downcallHandle(
        "QuerySecurityAccessMask",
        constants$231.QuerySecurityAccessMask$FUNC
    );
    static final FunctionDescriptor RevertToSelf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle RevertToSelf$MH = RuntimeHelper.downcallHandle(
        "RevertToSelf",
        constants$231.RevertToSelf$FUNC
    );
    static final FunctionDescriptor SetAclInformation$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetAclInformation$MH = RuntimeHelper.downcallHandle(
        "SetAclInformation",
        constants$231.SetAclInformation$FUNC
    );
    static final FunctionDescriptor SetFileSecurityW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetFileSecurityW$MH = RuntimeHelper.downcallHandle(
        "SetFileSecurityW",
        constants$231.SetFileSecurityW$FUNC
    );
}


