// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$349 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$349() {}
    static final FunctionDescriptor GetTextCharsetInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetTextCharsetInfo$MH = RuntimeHelper.downcallHandle(
        "GetTextCharsetInfo",
        constants$349.GetTextCharsetInfo$FUNC
    );
    static final FunctionDescriptor TranslateCharsetInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle TranslateCharsetInfo$MH = RuntimeHelper.downcallHandle(
        "TranslateCharsetInfo",
        constants$349.TranslateCharsetInfo$FUNC
    );
    static final FunctionDescriptor GetFontLanguageInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFontLanguageInfo$MH = RuntimeHelper.downcallHandle(
        "GetFontLanguageInfo",
        constants$349.GetFontLanguageInfo$FUNC
    );
    static final FunctionDescriptor GetCharacterPlacementA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetCharacterPlacementA$MH = RuntimeHelper.downcallHandle(
        "GetCharacterPlacementA",
        constants$349.GetCharacterPlacementA$FUNC
    );
    static final FunctionDescriptor GetCharacterPlacementW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetCharacterPlacementW$MH = RuntimeHelper.downcallHandle(
        "GetCharacterPlacementW",
        constants$349.GetCharacterPlacementW$FUNC
    );
    static final FunctionDescriptor GetFontUnicodeRanges$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFontUnicodeRanges$MH = RuntimeHelper.downcallHandle(
        "GetFontUnicodeRanges",
        constants$349.GetFontUnicodeRanges$FUNC
    );
}


