// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _DISK_CONTROLLER_NUMBER DISK_CONTROLLER_NUMBER;
 * }
 */
public final class DISK_CONTROLLER_NUMBER extends _DISK_CONTROLLER_NUMBER {

    // Suppresses default constructor, ensuring non-instantiability.
    private DISK_CONTROLLER_NUMBER() {}
}


