// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct tagEMRSETVIEWPORTORGEX EMRSETWINDOWORGEX;
 * }
 */
public final class EMRSETWINDOWORGEX extends tagEMRSETVIEWPORTORGEX {

    // Suppresses default constructor, ensuring non-instantiability.
    private EMRSETWINDOWORGEX() {}
}


