// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _ENCLAVE_CREATE_INFO_VBS_BASIC ENCLAVE_CREATE_INFO_VBS_BASIC;
 * }
 */
public final class ENCLAVE_CREATE_INFO_VBS_BASIC extends _ENCLAVE_CREATE_INFO_VBS_BASIC {

    // Suppresses default constructor, ensuring non-instantiability.
    private ENCLAVE_CREATE_INFO_VBS_BASIC() {}
}


