// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct tagEXTLOGPEN32 EXTLOGPEN32;
 * }
 */
public final class EXTLOGPEN32 extends tagEXTLOGPEN32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private EXTLOGPEN32() {}
}


