// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _FILE_DESIRED_STORAGE_CLASS_INFORMATION FILE_DESIRED_STORAGE_CLASS_INFORMATION;
 * }
 */
public final class FILE_DESIRED_STORAGE_CLASS_INFORMATION extends _FILE_DESIRED_STORAGE_CLASS_INFORMATION {

    // Suppresses default constructor, ensuring non-instantiability.
    private FILE_DESIRED_STORAGE_CLASS_INFORMATION() {}
}


