// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct IThumbnailExtractorVtbl {
 *     HRESULT (*QueryInterface)(IThumbnailExtractor*,const IID*,void**);
 *     ULONG (*AddRef)(IThumbnailExtractor*);
 *     ULONG (*Release)(IThumbnailExtractor*);
 *     HRESULT (*ExtractThumbnail)(IThumbnailExtractor*,IStorage*,ULONG,ULONG,ULONG*,ULONG*,HBITMAP*);
 *     HRESULT (*OnFileUpdated)(IThumbnailExtractor*,IStorage*);
 * };
 * }
 */
public class IThumbnailExtractorVtbl {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("QueryInterface"),
        Constants$root.C_POINTER$LAYOUT.withName("AddRef"),
        Constants$root.C_POINTER$LAYOUT.withName("Release"),
        Constants$root.C_POINTER$LAYOUT.withName("ExtractThumbnail"),
        Constants$root.C_POINTER$LAYOUT.withName("OnFileUpdated")
    ).withName("IThumbnailExtractorVtbl");
    public static MemoryLayout $LAYOUT() {
        return IThumbnailExtractorVtbl.$struct$LAYOUT;
    }
    static final FunctionDescriptor QueryInterface$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor QueryInterface_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryInterface_UP$MH = RuntimeHelper.upcallHandle(QueryInterface.class, "apply", IThumbnailExtractorVtbl.QueryInterface_UP$FUNC);
    static final FunctionDescriptor QueryInterface_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryInterface_DOWN$MH = RuntimeHelper.downcallHandle(
        IThumbnailExtractorVtbl.QueryInterface_DOWN$FUNC
    );
    /**
     * {@snippet :
 * HRESULT (*QueryInterface)(IThumbnailExtractor*,const IID*,void**);
     * }
     */
    public interface QueryInterface {

        int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2);
        static MemorySegment allocate(QueryInterface fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(IThumbnailExtractorVtbl.QueryInterface_UP$MH, fi, IThumbnailExtractorVtbl.QueryInterface$FUNC, scope);
        }
        static QueryInterface ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2) -> {
                try {
                    return (int)IThumbnailExtractorVtbl.QueryInterface_DOWN$MH.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle QueryInterface$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("QueryInterface"));
    public static VarHandle QueryInterface$VH() {
        return IThumbnailExtractorVtbl.QueryInterface$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * HRESULT (*QueryInterface)(IThumbnailExtractor*,const IID*,void**);
     * }
     */
    public static MemorySegment QueryInterface$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.QueryInterface$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * HRESULT (*QueryInterface)(IThumbnailExtractor*,const IID*,void**);
     * }
     */
    public static void QueryInterface$set(MemorySegment seg, MemorySegment x) {
        IThumbnailExtractorVtbl.QueryInterface$VH.set(seg, x);
    }
    public static MemorySegment QueryInterface$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.QueryInterface$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void QueryInterface$set(MemorySegment seg, long index, MemorySegment x) {
        IThumbnailExtractorVtbl.QueryInterface$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static QueryInterface QueryInterface(MemorySegment segment, SegmentScope scope) {
        return QueryInterface.ofAddress(QueryInterface$get(segment), scope);
    }
    static final FunctionDescriptor AddRef$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor AddRef_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AddRef_UP$MH = RuntimeHelper.upcallHandle(AddRef.class, "apply", IThumbnailExtractorVtbl.AddRef_UP$FUNC);
    static final FunctionDescriptor AddRef_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AddRef_DOWN$MH = RuntimeHelper.downcallHandle(
        IThumbnailExtractorVtbl.AddRef_DOWN$FUNC
    );
    /**
     * {@snippet :
 * ULONG (*AddRef)(IThumbnailExtractor*);
     * }
     */
    public interface AddRef {

        int apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(AddRef fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(IThumbnailExtractorVtbl.AddRef_UP$MH, fi, IThumbnailExtractorVtbl.AddRef$FUNC, scope);
        }
        static AddRef ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (int)IThumbnailExtractorVtbl.AddRef_DOWN$MH.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle AddRef$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("AddRef"));
    public static VarHandle AddRef$VH() {
        return IThumbnailExtractorVtbl.AddRef$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * ULONG (*AddRef)(IThumbnailExtractor*);
     * }
     */
    public static MemorySegment AddRef$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.AddRef$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * ULONG (*AddRef)(IThumbnailExtractor*);
     * }
     */
    public static void AddRef$set(MemorySegment seg, MemorySegment x) {
        IThumbnailExtractorVtbl.AddRef$VH.set(seg, x);
    }
    public static MemorySegment AddRef$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.AddRef$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void AddRef$set(MemorySegment seg, long index, MemorySegment x) {
        IThumbnailExtractorVtbl.AddRef$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static AddRef AddRef(MemorySegment segment, SegmentScope scope) {
        return AddRef.ofAddress(AddRef$get(segment), scope);
    }
    static final FunctionDescriptor Release$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor Release_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle Release_UP$MH = RuntimeHelper.upcallHandle(Release.class, "apply", IThumbnailExtractorVtbl.Release_UP$FUNC);
    static final FunctionDescriptor Release_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle Release_DOWN$MH = RuntimeHelper.downcallHandle(
        IThumbnailExtractorVtbl.Release_DOWN$FUNC
    );
    /**
     * {@snippet :
 * ULONG (*Release)(IThumbnailExtractor*);
     * }
     */
    public interface Release {

        int apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(Release fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(IThumbnailExtractorVtbl.Release_UP$MH, fi, IThumbnailExtractorVtbl.Release$FUNC, scope);
        }
        static Release ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (int)IThumbnailExtractorVtbl.Release_DOWN$MH.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Release$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("Release"));
    public static VarHandle Release$VH() {
        return IThumbnailExtractorVtbl.Release$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * ULONG (*Release)(IThumbnailExtractor*);
     * }
     */
    public static MemorySegment Release$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.Release$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * ULONG (*Release)(IThumbnailExtractor*);
     * }
     */
    public static void Release$set(MemorySegment seg, MemorySegment x) {
        IThumbnailExtractorVtbl.Release$VH.set(seg, x);
    }
    public static MemorySegment Release$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.Release$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Release$set(MemorySegment seg, long index, MemorySegment x) {
        IThumbnailExtractorVtbl.Release$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Release Release(MemorySegment segment, SegmentScope scope) {
        return Release.ofAddress(Release$get(segment), scope);
    }
    static final FunctionDescriptor ExtractThumbnail$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor ExtractThumbnail_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExtractThumbnail_UP$MH = RuntimeHelper.upcallHandle(ExtractThumbnail.class, "apply", IThumbnailExtractorVtbl.ExtractThumbnail_UP$FUNC);
    static final FunctionDescriptor ExtractThumbnail_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExtractThumbnail_DOWN$MH = RuntimeHelper.downcallHandle(
        IThumbnailExtractorVtbl.ExtractThumbnail_DOWN$FUNC
    );
    /**
     * {@snippet :
 * HRESULT (*ExtractThumbnail)(IThumbnailExtractor*,IStorage*,ULONG,ULONG,ULONG*,ULONG*,HBITMAP*);
     * }
     */
    public interface ExtractThumbnail {

        int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, int _x2, int _x3, java.lang.foreign.MemorySegment _x4, java.lang.foreign.MemorySegment _x5, java.lang.foreign.MemorySegment _x6);
        static MemorySegment allocate(ExtractThumbnail fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(IThumbnailExtractorVtbl.ExtractThumbnail_UP$MH, fi, IThumbnailExtractorVtbl.ExtractThumbnail$FUNC, scope);
        }
        static ExtractThumbnail ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, int __x2, int __x3, java.lang.foreign.MemorySegment __x4, java.lang.foreign.MemorySegment __x5, java.lang.foreign.MemorySegment __x6) -> {
                try {
                    return (int)IThumbnailExtractorVtbl.ExtractThumbnail_DOWN$MH.invokeExact(symbol, __x0, __x1, __x2, __x3, __x4, __x5, __x6);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle ExtractThumbnail$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("ExtractThumbnail"));
    public static VarHandle ExtractThumbnail$VH() {
        return IThumbnailExtractorVtbl.ExtractThumbnail$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * HRESULT (*ExtractThumbnail)(IThumbnailExtractor*,IStorage*,ULONG,ULONG,ULONG*,ULONG*,HBITMAP*);
     * }
     */
    public static MemorySegment ExtractThumbnail$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.ExtractThumbnail$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * HRESULT (*ExtractThumbnail)(IThumbnailExtractor*,IStorage*,ULONG,ULONG,ULONG*,ULONG*,HBITMAP*);
     * }
     */
    public static void ExtractThumbnail$set(MemorySegment seg, MemorySegment x) {
        IThumbnailExtractorVtbl.ExtractThumbnail$VH.set(seg, x);
    }
    public static MemorySegment ExtractThumbnail$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.ExtractThumbnail$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ExtractThumbnail$set(MemorySegment seg, long index, MemorySegment x) {
        IThumbnailExtractorVtbl.ExtractThumbnail$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static ExtractThumbnail ExtractThumbnail(MemorySegment segment, SegmentScope scope) {
        return ExtractThumbnail.ofAddress(ExtractThumbnail$get(segment), scope);
    }
    static final FunctionDescriptor OnFileUpdated$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor OnFileUpdated_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OnFileUpdated_UP$MH = RuntimeHelper.upcallHandle(OnFileUpdated.class, "apply", IThumbnailExtractorVtbl.OnFileUpdated_UP$FUNC);
    static final FunctionDescriptor OnFileUpdated_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OnFileUpdated_DOWN$MH = RuntimeHelper.downcallHandle(
        IThumbnailExtractorVtbl.OnFileUpdated_DOWN$FUNC
    );
    /**
     * {@snippet :
 * HRESULT (*OnFileUpdated)(IThumbnailExtractor*,IStorage*);
     * }
     */
    public interface OnFileUpdated {

        int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1);
        static MemorySegment allocate(OnFileUpdated fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(IThumbnailExtractorVtbl.OnFileUpdated_UP$MH, fi, IThumbnailExtractorVtbl.OnFileUpdated$FUNC, scope);
        }
        static OnFileUpdated ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1) -> {
                try {
                    return (int)IThumbnailExtractorVtbl.OnFileUpdated_DOWN$MH.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle OnFileUpdated$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("OnFileUpdated"));
    public static VarHandle OnFileUpdated$VH() {
        return IThumbnailExtractorVtbl.OnFileUpdated$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * HRESULT (*OnFileUpdated)(IThumbnailExtractor*,IStorage*);
     * }
     */
    public static MemorySegment OnFileUpdated$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.OnFileUpdated$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * HRESULT (*OnFileUpdated)(IThumbnailExtractor*,IStorage*);
     * }
     */
    public static void OnFileUpdated$set(MemorySegment seg, MemorySegment x) {
        IThumbnailExtractorVtbl.OnFileUpdated$VH.set(seg, x);
    }
    public static MemorySegment OnFileUpdated$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)IThumbnailExtractorVtbl.OnFileUpdated$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void OnFileUpdated$set(MemorySegment seg, long index, MemorySegment x) {
        IThumbnailExtractorVtbl.OnFileUpdated$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static OnFileUpdated OnFileUpdated(MemorySegment segment, SegmentScope scope) {
        return OnFileUpdated.ofAddress(OnFileUpdated$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


