// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * long (*LPFNGETCLASSOBJECT)(struct _GUID*,struct _GUID*,void**);
 * }
 */
public interface LPFNGETCLASSOBJECT {

    int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2);
    static MemorySegment allocate(LPFNGETCLASSOBJECT fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$992.LPFNGETCLASSOBJECT_UP$MH, fi, constants$992.LPFNGETCLASSOBJECT$FUNC, scope);
    }
    static LPFNGETCLASSOBJECT ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2) -> {
            try {
                return (int)constants$992.LPFNGETCLASSOBJECT_DOWN$MH.invokeExact(symbol, __x0, __x1, __x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


