// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct tagNC_ADDRESS NC_ADDRESS;
 * }
 */
public final class NC_ADDRESS extends tagNC_ADDRESS {

    // Suppresses default constructor, ensuring non-instantiability.
    private NC_ADDRESS() {}
}


