// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * RPC_STATUS (*RPC_FORWARD_FUNCTION)(UUID* InterfaceId,RPC_VERSION* InterfaceVersion,UUID* ObjectId,unsigned char* Rpcpro,void** ppDestEndpoint);
 * }
 */
public interface RPC_FORWARD_FUNCTION {

    int apply(java.lang.foreign.MemorySegment Context, java.lang.foreign.MemorySegment SessionIdPresent, java.lang.foreign.MemorySegment SessionId, java.lang.foreign.MemorySegment ResourceIdPresent, java.lang.foreign.MemorySegment ResourceId);
    static MemorySegment allocate(RPC_FORWARD_FUNCTION fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$659.RPC_FORWARD_FUNCTION_UP$MH, fi, constants$659.RPC_FORWARD_FUNCTION$FUNC, scope);
    }
    static RPC_FORWARD_FUNCTION ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _Context, java.lang.foreign.MemorySegment _SessionIdPresent, java.lang.foreign.MemorySegment _SessionId, java.lang.foreign.MemorySegment _ResourceIdPresent, java.lang.foreign.MemorySegment _ResourceId) -> {
            try {
                return (int)constants$659.RPC_FORWARD_FUNCTION_DOWN$MH.invokeExact(symbol, _Context, _SessionIdPresent, _SessionId, _ResourceIdPresent, _ResourceId);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


