// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _SECURITY_QUALITY_OF_SERVICE SECURITY_QUALITY_OF_SERVICE;
 * }
 */
public final class SECURITY_QUALITY_OF_SERVICE extends _SECURITY_QUALITY_OF_SERVICE {

    // Suppresses default constructor, ensuring non-instantiability.
    private SECURITY_QUALITY_OF_SERVICE() {}
}


