// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _SERVICE_TRIGGER_INFO SERVICE_TRIGGER_INFO;
 * }
 */
public final class SERVICE_TRIGGER_INFO extends _SERVICE_TRIGGER_INFO {

    // Suppresses default constructor, ensuring non-instantiability.
    private SERVICE_TRIGGER_INFO() {}
}


