// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _SERVICE_REQUIRED_PRIVILEGES_INFOW SERVICE_REQUIRED_PRIVILEGES_INFOW;
 * }
 */
public final class SERVICE_REQUIRED_PRIVILEGES_INFOW extends _SERVICE_REQUIRED_PRIVILEGES_INFOW {

    // Suppresses default constructor, ensuring non-instantiability.
    private SERVICE_REQUIRED_PRIVILEGES_INFOW() {}
}


