// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct tagPELARRAY {
 *     LONG paXCount;
 *     LONG paYCount;
 *     LONG paXExt;
 *     LONG paYExt;
 *     BYTE paRGBs;
 * };
 * }
 */
public class tagPELARRAY {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("paXCount"),
        Constants$root.C_LONG$LAYOUT.withName("paYCount"),
        Constants$root.C_LONG$LAYOUT.withName("paXExt"),
        Constants$root.C_LONG$LAYOUT.withName("paYExt"),
        Constants$root.C_CHAR$LAYOUT.withName("paRGBs"),
        MemoryLayout.paddingLayout(24)
    ).withName("tagPELARRAY");
    public static MemoryLayout $LAYOUT() {
        return tagPELARRAY.$struct$LAYOUT;
    }
    static final VarHandle paXCount$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("paXCount"));
    public static VarHandle paXCount$VH() {
        return tagPELARRAY.paXCount$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LONG paXCount;
     * }
     */
    public static int paXCount$get(MemorySegment seg) {
        return (int)tagPELARRAY.paXCount$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LONG paXCount;
     * }
     */
    public static void paXCount$set(MemorySegment seg, int x) {
        tagPELARRAY.paXCount$VH.set(seg, x);
    }
    public static int paXCount$get(MemorySegment seg, long index) {
        return (int)tagPELARRAY.paXCount$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void paXCount$set(MemorySegment seg, long index, int x) {
        tagPELARRAY.paXCount$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle paYCount$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("paYCount"));
    public static VarHandle paYCount$VH() {
        return tagPELARRAY.paYCount$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LONG paYCount;
     * }
     */
    public static int paYCount$get(MemorySegment seg) {
        return (int)tagPELARRAY.paYCount$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LONG paYCount;
     * }
     */
    public static void paYCount$set(MemorySegment seg, int x) {
        tagPELARRAY.paYCount$VH.set(seg, x);
    }
    public static int paYCount$get(MemorySegment seg, long index) {
        return (int)tagPELARRAY.paYCount$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void paYCount$set(MemorySegment seg, long index, int x) {
        tagPELARRAY.paYCount$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle paXExt$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("paXExt"));
    public static VarHandle paXExt$VH() {
        return tagPELARRAY.paXExt$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LONG paXExt;
     * }
     */
    public static int paXExt$get(MemorySegment seg) {
        return (int)tagPELARRAY.paXExt$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LONG paXExt;
     * }
     */
    public static void paXExt$set(MemorySegment seg, int x) {
        tagPELARRAY.paXExt$VH.set(seg, x);
    }
    public static int paXExt$get(MemorySegment seg, long index) {
        return (int)tagPELARRAY.paXExt$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void paXExt$set(MemorySegment seg, long index, int x) {
        tagPELARRAY.paXExt$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle paYExt$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("paYExt"));
    public static VarHandle paYExt$VH() {
        return tagPELARRAY.paYExt$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LONG paYExt;
     * }
     */
    public static int paYExt$get(MemorySegment seg) {
        return (int)tagPELARRAY.paYExt$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LONG paYExt;
     * }
     */
    public static void paYExt$set(MemorySegment seg, int x) {
        tagPELARRAY.paYExt$VH.set(seg, x);
    }
    public static int paYExt$get(MemorySegment seg, long index) {
        return (int)tagPELARRAY.paYExt$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void paYExt$set(MemorySegment seg, long index, int x) {
        tagPELARRAY.paYExt$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle paRGBs$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("paRGBs"));
    public static VarHandle paRGBs$VH() {
        return tagPELARRAY.paRGBs$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BYTE paRGBs;
     * }
     */
    public static byte paRGBs$get(MemorySegment seg) {
        return (byte)tagPELARRAY.paRGBs$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BYTE paRGBs;
     * }
     */
    public static void paRGBs$set(MemorySegment seg, byte x) {
        tagPELARRAY.paRGBs$VH.set(seg, x);
    }
    public static byte paRGBs$get(MemorySegment seg, long index) {
        return (byte)tagPELARRAY.paRGBs$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void paRGBs$set(MemorySegment seg, long index, byte x) {
        tagPELARRAY.paRGBs$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


