// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct tagStorageLayout {
 *     DWORD LayoutType;
 *     OLECHAR* pwcsElementName;
 *     LARGE_INTEGER cOffset;
 *     LARGE_INTEGER cBytes;
 * };
 * }
 */
public class tagStorageLayout {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("LayoutType"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("pwcsElementName"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                Constants$root.C_LONG$LAYOUT.withName("LowPart"),
                Constants$root.C_LONG$LAYOUT.withName("HighPart")
            ).withName("$anon$0"),
            MemoryLayout.structLayout(
                Constants$root.C_LONG$LAYOUT.withName("LowPart"),
                Constants$root.C_LONG$LAYOUT.withName("HighPart")
            ).withName("u"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("QuadPart")
        ).withName("cOffset"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                Constants$root.C_LONG$LAYOUT.withName("LowPart"),
                Constants$root.C_LONG$LAYOUT.withName("HighPart")
            ).withName("$anon$0"),
            MemoryLayout.structLayout(
                Constants$root.C_LONG$LAYOUT.withName("LowPart"),
                Constants$root.C_LONG$LAYOUT.withName("HighPart")
            ).withName("u"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("QuadPart")
        ).withName("cBytes")
    ).withName("tagStorageLayout");
    public static MemoryLayout $LAYOUT() {
        return tagStorageLayout.$struct$LAYOUT;
    }
    static final VarHandle LayoutType$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("LayoutType"));
    public static VarHandle LayoutType$VH() {
        return tagStorageLayout.LayoutType$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD LayoutType;
     * }
     */
    public static int LayoutType$get(MemorySegment seg) {
        return (int)tagStorageLayout.LayoutType$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD LayoutType;
     * }
     */
    public static void LayoutType$set(MemorySegment seg, int x) {
        tagStorageLayout.LayoutType$VH.set(seg, x);
    }
    public static int LayoutType$get(MemorySegment seg, long index) {
        return (int)tagStorageLayout.LayoutType$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void LayoutType$set(MemorySegment seg, long index, int x) {
        tagStorageLayout.LayoutType$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle pwcsElementName$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("pwcsElementName"));
    public static VarHandle pwcsElementName$VH() {
        return tagStorageLayout.pwcsElementName$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * OLECHAR* pwcsElementName;
     * }
     */
    public static MemorySegment pwcsElementName$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)tagStorageLayout.pwcsElementName$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * OLECHAR* pwcsElementName;
     * }
     */
    public static void pwcsElementName$set(MemorySegment seg, MemorySegment x) {
        tagStorageLayout.pwcsElementName$VH.set(seg, x);
    }
    public static MemorySegment pwcsElementName$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)tagStorageLayout.pwcsElementName$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void pwcsElementName$set(MemorySegment seg, long index, MemorySegment x) {
        tagStorageLayout.pwcsElementName$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment cOffset$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static MemorySegment cBytes$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


