// Generated by jextract

package com.microsoft.win32;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct tagWNDCLASSA {
 *     UINT style;
 *     WNDPROC lpfnWndProc;
 *     int cbClsExtra;
 *     int cbWndExtra;
 *     HINSTANCE hInstance;
 *     HICON hIcon;
 *     HCURSOR hCursor;
 *     HBRUSH hbrBackground;
 *     LPCSTR lpszMenuName;
 *     LPCSTR lpszClassName;
 * };
 * }
 */
public class tagWNDCLASSA {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("style"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("lpfnWndProc"),
        Constants$root.C_LONG$LAYOUT.withName("cbClsExtra"),
        Constants$root.C_LONG$LAYOUT.withName("cbWndExtra"),
        Constants$root.C_POINTER$LAYOUT.withName("hInstance"),
        Constants$root.C_POINTER$LAYOUT.withName("hIcon"),
        Constants$root.C_POINTER$LAYOUT.withName("hCursor"),
        Constants$root.C_POINTER$LAYOUT.withName("hbrBackground"),
        Constants$root.C_POINTER$LAYOUT.withName("lpszMenuName"),
        Constants$root.C_POINTER$LAYOUT.withName("lpszClassName")
    ).withName("tagWNDCLASSA");
    public static MemoryLayout $LAYOUT() {
        return tagWNDCLASSA.$struct$LAYOUT;
    }
    static final VarHandle style$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("style"));
    public static VarHandle style$VH() {
        return tagWNDCLASSA.style$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UINT style;
     * }
     */
    public static int style$get(MemorySegment seg) {
        return (int)tagWNDCLASSA.style$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UINT style;
     * }
     */
    public static void style$set(MemorySegment seg, int x) {
        tagWNDCLASSA.style$VH.set(seg, x);
    }
    public static int style$get(MemorySegment seg, long index) {
        return (int)tagWNDCLASSA.style$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void style$set(MemorySegment seg, long index, int x) {
        tagWNDCLASSA.style$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle lpfnWndProc$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("lpfnWndProc"));
    public static VarHandle lpfnWndProc$VH() {
        return tagWNDCLASSA.lpfnWndProc$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * WNDPROC lpfnWndProc;
     * }
     */
    public static MemorySegment lpfnWndProc$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.lpfnWndProc$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * WNDPROC lpfnWndProc;
     * }
     */
    public static void lpfnWndProc$set(MemorySegment seg, MemorySegment x) {
        tagWNDCLASSA.lpfnWndProc$VH.set(seg, x);
    }
    public static MemorySegment lpfnWndProc$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.lpfnWndProc$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void lpfnWndProc$set(MemorySegment seg, long index, MemorySegment x) {
        tagWNDCLASSA.lpfnWndProc$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static WNDPROC lpfnWndProc(MemorySegment segment, SegmentScope scope) {
        return WNDPROC.ofAddress(lpfnWndProc$get(segment), scope);
    }
    static final VarHandle cbClsExtra$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("cbClsExtra"));
    public static VarHandle cbClsExtra$VH() {
        return tagWNDCLASSA.cbClsExtra$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int cbClsExtra;
     * }
     */
    public static int cbClsExtra$get(MemorySegment seg) {
        return (int)tagWNDCLASSA.cbClsExtra$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int cbClsExtra;
     * }
     */
    public static void cbClsExtra$set(MemorySegment seg, int x) {
        tagWNDCLASSA.cbClsExtra$VH.set(seg, x);
    }
    public static int cbClsExtra$get(MemorySegment seg, long index) {
        return (int)tagWNDCLASSA.cbClsExtra$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void cbClsExtra$set(MemorySegment seg, long index, int x) {
        tagWNDCLASSA.cbClsExtra$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle cbWndExtra$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("cbWndExtra"));
    public static VarHandle cbWndExtra$VH() {
        return tagWNDCLASSA.cbWndExtra$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int cbWndExtra;
     * }
     */
    public static int cbWndExtra$get(MemorySegment seg) {
        return (int)tagWNDCLASSA.cbWndExtra$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int cbWndExtra;
     * }
     */
    public static void cbWndExtra$set(MemorySegment seg, int x) {
        tagWNDCLASSA.cbWndExtra$VH.set(seg, x);
    }
    public static int cbWndExtra$get(MemorySegment seg, long index) {
        return (int)tagWNDCLASSA.cbWndExtra$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void cbWndExtra$set(MemorySegment seg, long index, int x) {
        tagWNDCLASSA.cbWndExtra$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle hInstance$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("hInstance"));
    public static VarHandle hInstance$VH() {
        return tagWNDCLASSA.hInstance$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * HINSTANCE hInstance;
     * }
     */
    public static MemorySegment hInstance$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.hInstance$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * HINSTANCE hInstance;
     * }
     */
    public static void hInstance$set(MemorySegment seg, MemorySegment x) {
        tagWNDCLASSA.hInstance$VH.set(seg, x);
    }
    public static MemorySegment hInstance$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.hInstance$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void hInstance$set(MemorySegment seg, long index, MemorySegment x) {
        tagWNDCLASSA.hInstance$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle hIcon$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("hIcon"));
    public static VarHandle hIcon$VH() {
        return tagWNDCLASSA.hIcon$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * HICON hIcon;
     * }
     */
    public static MemorySegment hIcon$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.hIcon$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * HICON hIcon;
     * }
     */
    public static void hIcon$set(MemorySegment seg, MemorySegment x) {
        tagWNDCLASSA.hIcon$VH.set(seg, x);
    }
    public static MemorySegment hIcon$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.hIcon$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void hIcon$set(MemorySegment seg, long index, MemorySegment x) {
        tagWNDCLASSA.hIcon$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle hCursor$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("hCursor"));
    public static VarHandle hCursor$VH() {
        return tagWNDCLASSA.hCursor$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * HCURSOR hCursor;
     * }
     */
    public static MemorySegment hCursor$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.hCursor$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * HCURSOR hCursor;
     * }
     */
    public static void hCursor$set(MemorySegment seg, MemorySegment x) {
        tagWNDCLASSA.hCursor$VH.set(seg, x);
    }
    public static MemorySegment hCursor$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.hCursor$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void hCursor$set(MemorySegment seg, long index, MemorySegment x) {
        tagWNDCLASSA.hCursor$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle hbrBackground$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("hbrBackground"));
    public static VarHandle hbrBackground$VH() {
        return tagWNDCLASSA.hbrBackground$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * HBRUSH hbrBackground;
     * }
     */
    public static MemorySegment hbrBackground$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.hbrBackground$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * HBRUSH hbrBackground;
     * }
     */
    public static void hbrBackground$set(MemorySegment seg, MemorySegment x) {
        tagWNDCLASSA.hbrBackground$VH.set(seg, x);
    }
    public static MemorySegment hbrBackground$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.hbrBackground$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void hbrBackground$set(MemorySegment seg, long index, MemorySegment x) {
        tagWNDCLASSA.hbrBackground$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle lpszMenuName$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("lpszMenuName"));
    public static VarHandle lpszMenuName$VH() {
        return tagWNDCLASSA.lpszMenuName$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LPCSTR lpszMenuName;
     * }
     */
    public static MemorySegment lpszMenuName$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.lpszMenuName$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LPCSTR lpszMenuName;
     * }
     */
    public static void lpszMenuName$set(MemorySegment seg, MemorySegment x) {
        tagWNDCLASSA.lpszMenuName$VH.set(seg, x);
    }
    public static MemorySegment lpszMenuName$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.lpszMenuName$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void lpszMenuName$set(MemorySegment seg, long index, MemorySegment x) {
        tagWNDCLASSA.lpszMenuName$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle lpszClassName$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("lpszClassName"));
    public static VarHandle lpszClassName$VH() {
        return tagWNDCLASSA.lpszClassName$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LPCSTR lpszClassName;
     * }
     */
    public static MemorySegment lpszClassName$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.lpszClassName$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LPCSTR lpszClassName;
     * }
     */
    public static void lpszClassName$set(MemorySegment seg, MemorySegment x) {
        tagWNDCLASSA.lpszClassName$VH.set(seg, x);
    }
    public static MemorySegment lpszClassName$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)tagWNDCLASSA.lpszClassName$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void lpszClassName$set(MemorySegment seg, long index, MemorySegment x) {
        tagWNDCLASSA.lpszClassName$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


